#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLight
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aplixH_HFU_Test")]
	public partial class LINQtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LINQtoSQLDataContext() : 
				base(global::CRMLight.Properties.Settings.Default.aplixH_HFU_TestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crm_Anmelden")]
		public ISingleResult<crm_AnmeldenResult> crm_Anmelden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_Benutzer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_Passwort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_Benutzer, i_Passwort);
			return ((ISingleResult<crm_AnmeldenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crm_GetPendenzen")]
		public ISingleResult<crm_GetPendenzenResult> crm_GetPendenzen([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_SessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_KontaktID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_SessionID, i_KontaktID);
			return ((ISingleResult<crm_GetPendenzenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crm_SetPendenz")]
		public ISingleResult<crm_SetPendenzResult> crm_SetPendenz([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_SessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_KontaktID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_PendenzID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_Modus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> i_Termin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_MitarbeiterID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_Titel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8000)")] string i_Beschreibung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_SessionID, i_KontaktID, i_PendenzID, i_Modus, i_Termin, i_MitarbeiterID, i_Titel, i_Beschreibung);
			return ((ISingleResult<crm_SetPendenzResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crm_GetKontakte")]
		public ISingleResult<crm_GetKontakteResult> crm_GetKontakte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_SessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_FilterID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_SessionID, i_FilterID);
			return ((ISingleResult<crm_GetKontakteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crm_GetStammdaten")]
		public ISingleResult<crm_GetStammdatenResult> crm_GetStammdaten([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_SessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_Tabelle)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_SessionID, i_Tabelle);
			return ((ISingleResult<crm_GetStammdatenResult>)(result.ReturnValue));
		}
	}
	
	public partial class crm_AnmeldenResult
	{
		
		private System.Nullable<int> _Fehler;
		
		private string _Fehlermeldung;
		
		private System.Nullable<int> _SessionID;
		
		public crm_AnmeldenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehler", DbType="Int")]
		public System.Nullable<int> Fehler
		{
			get
			{
				return this._Fehler;
			}
			set
			{
				if ((this._Fehler != value))
				{
					this._Fehler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehlermeldung", DbType="VarChar(255)")]
		public string Fehlermeldung
		{
			get
			{
				return this._Fehlermeldung;
			}
			set
			{
				if ((this._Fehlermeldung != value))
				{
					this._Fehlermeldung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="Int")]
		public System.Nullable<int> SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this._SessionID = value;
				}
			}
		}
	}
	
	public partial class crm_GetPendenzenResult
	{
		
		private int _Fehler;
		
		private string _FehlerMeldung;
		
		private int _PendenzID;
		
		private int _MitarbeiterID;
		
		private System.Nullable<int> _Termin;
		
		private string _Titel;
		
		private string _Beschreibung;
		
		private System.Nullable<bool> _Erledigt;
		
		private string _Quelle;
		
		public crm_GetPendenzenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehler", DbType="Int NOT NULL")]
		public int Fehler
		{
			get
			{
				return this._Fehler;
			}
			set
			{
				if ((this._Fehler != value))
				{
					this._Fehler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FehlerMeldung", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
		public string FehlerMeldung
		{
			get
			{
				return this._FehlerMeldung;
			}
			set
			{
				if ((this._FehlerMeldung != value))
				{
					this._FehlerMeldung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PendenzID", DbType="Int NOT NULL")]
		public int PendenzID
		{
			get
			{
				return this._PendenzID;
			}
			set
			{
				if ((this._PendenzID != value))
				{
					this._PendenzID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MitarbeiterID", DbType="Int NOT NULL")]
		public int MitarbeiterID
		{
			get
			{
				return this._MitarbeiterID;
			}
			set
			{
				if ((this._MitarbeiterID != value))
				{
					this._MitarbeiterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="Int")]
		public System.Nullable<int> Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this._Termin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="VarChar(50)")]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this._Titel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(8000)")]
		public string Beschreibung
		{
			get
			{
				return this._Beschreibung;
			}
			set
			{
				if ((this._Beschreibung != value))
				{
					this._Beschreibung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Erledigt", DbType="Bit")]
		public System.Nullable<bool> Erledigt
		{
			get
			{
				return this._Erledigt;
			}
			set
			{
				if ((this._Erledigt != value))
				{
					this._Erledigt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quelle", DbType="VarChar(255)")]
		public string Quelle
		{
			get
			{
				return this._Quelle;
			}
			set
			{
				if ((this._Quelle != value))
				{
					this._Quelle = value;
				}
			}
		}
	}
	
	public partial class crm_SetPendenzResult
	{
		
		private System.Nullable<int> _Fehler;
		
		private string _Fehlermeldung;
		
		public crm_SetPendenzResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehler", DbType="Int")]
		public System.Nullable<int> Fehler
		{
			get
			{
				return this._Fehler;
			}
			set
			{
				if ((this._Fehler != value))
				{
					this._Fehler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehlermeldung", DbType="VarChar(255)")]
		public string Fehlermeldung
		{
			get
			{
				return this._Fehlermeldung;
			}
			set
			{
				if ((this._Fehlermeldung != value))
				{
					this._Fehlermeldung = value;
				}
			}
		}
	}
	
	public partial class crm_GetKontakteResult
	{
		
		private System.Nullable<int> _Fehler;
		
		private string _FehlerMeldung;
		
		private System.Nullable<int> _KontaktID;
		
		private string _Firma;
		
		private string _Name;
		
		private string _Vorname;
		
		private string _Strasse;
		
		private string _PLZ;
		
		private string _Ort;
		
		private string _Telefon;
		
		private string _Mobile;
		
		private string _eMail;
		
		private string _Bemerkung;
		
		private string _Interessen;
		
		private System.Nullable<System.DateTime> _AktionTermin;
		
		private string _AktionBeschreibung;
		
		private System.Nullable<int> _AktionMitarbeiterID;
		
		public crm_GetKontakteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehler", DbType="Int")]
		public System.Nullable<int> Fehler
		{
			get
			{
				return this._Fehler;
			}
			set
			{
				if ((this._Fehler != value))
				{
					this._Fehler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FehlerMeldung", DbType="VarChar(255)")]
		public string FehlerMeldung
		{
			get
			{
				return this._FehlerMeldung;
			}
			set
			{
				if ((this._FehlerMeldung != value))
				{
					this._FehlerMeldung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KontaktID", DbType="Int")]
		public System.Nullable<int> KontaktID
		{
			get
			{
				return this._KontaktID;
			}
			set
			{
				if ((this._KontaktID != value))
				{
					this._KontaktID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(100)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this._Firma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vorname", DbType="VarChar(50)")]
		public string Vorname
		{
			get
			{
				return this._Vorname;
			}
			set
			{
				if ((this._Vorname != value))
				{
					this._Vorname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strasse", DbType="VarChar(150)")]
		public string Strasse
		{
			get
			{
				return this._Strasse;
			}
			set
			{
				if ((this._Strasse != value))
				{
					this._Strasse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLZ", DbType="VarChar(10)")]
		public string PLZ
		{
			get
			{
				return this._PLZ;
			}
			set
			{
				if ((this._PLZ != value))
				{
					this._PLZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ort", DbType="VarChar(50)")]
		public string Ort
		{
			get
			{
				return this._Ort;
			}
			set
			{
				if ((this._Ort != value))
				{
					this._Ort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this._Telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="VarChar(100)")]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this._eMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bemerkung", DbType="VarChar(255)")]
		public string Bemerkung
		{
			get
			{
				return this._Bemerkung;
			}
			set
			{
				if ((this._Bemerkung != value))
				{
					this._Bemerkung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interessen", DbType="VarChar(255)")]
		public string Interessen
		{
			get
			{
				return this._Interessen;
			}
			set
			{
				if ((this._Interessen != value))
				{
					this._Interessen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktionTermin", DbType="DateTime")]
		public System.Nullable<System.DateTime> AktionTermin
		{
			get
			{
				return this._AktionTermin;
			}
			set
			{
				if ((this._AktionTermin != value))
				{
					this._AktionTermin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktionBeschreibung", DbType="VarChar(8000)")]
		public string AktionBeschreibung
		{
			get
			{
				return this._AktionBeschreibung;
			}
			set
			{
				if ((this._AktionBeschreibung != value))
				{
					this._AktionBeschreibung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktionMitarbeiterID", DbType="Int")]
		public System.Nullable<int> AktionMitarbeiterID
		{
			get
			{
				return this._AktionMitarbeiterID;
			}
			set
			{
				if ((this._AktionMitarbeiterID != value))
				{
					this._AktionMitarbeiterID = value;
				}
			}
		}
	}
	
	public partial class crm_GetStammdatenResult
	{
		
		private int _Fehler;
		
		private string _FehlerMeldung;
		
		private int _ID;
		
		private string _Code;
		
		private string _Bezeichnung;
		
		public crm_GetStammdatenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fehler", DbType="Int NOT NULL")]
		public int Fehler
		{
			get
			{
				return this._Fehler;
			}
			set
			{
				if ((this._Fehler != value))
				{
					this._Fehler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FehlerMeldung", DbType="VarChar(255)")]
		public string FehlerMeldung
		{
			get
			{
				return this._FehlerMeldung;
			}
			set
			{
				if ((this._FehlerMeldung != value))
				{
					this._FehlerMeldung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(20)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bezeichnung", DbType="VarChar(100)")]
		public string Bezeichnung
		{
			get
			{
				return this._Bezeichnung;
			}
			set
			{
				if ((this._Bezeichnung != value))
				{
					this._Bezeichnung = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
